Return-Path: <linux-next-owner@vger.kernel.org>
X-Original-To: lists+linux-next@lfdr.de
Delivered-To: lists+linux-next@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 009A81F0911
	for <lists+linux-next@lfdr.de>; Sun,  7 Jun 2020 02:03:21 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S1728883AbgFGADR (ORCPT <rfc822;lists+linux-next@lfdr.de>);
        Sat, 6 Jun 2020 20:03:17 -0400
Received: from mail-il1-f197.google.com ([209.85.166.197]:45910 "EHLO
        mail-il1-f197.google.com" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S1728821AbgFGADR (ORCPT
        <rfc822;linux-next@vger.kernel.org>); Sat, 6 Jun 2020 20:03:17 -0400
Received: by mail-il1-f197.google.com with SMTP id q24so9214841ili.12
        for <linux-next@vger.kernel.org>; Sat, 06 Jun 2020 17:03:15 -0700 (PDT)
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:date:message-id:subject:from:to;
        bh=J1SUHUAuYP0ErR/dAXOCHj8wL1Ryzt/cArP3DPalUi4=;
        b=myUQX2bdHWRPISoAZV4g00iUqjcFPGBve8YGtsBWXsmec8RDb/8AftX523FFuZFVE4
         9BPml08KcFU4VQ3kXMziSYTJiCdVuJWn2nBv6N0hDhZOjN3ODHNYNxBUgdnrn50lt7u1
         vEzbZJaDp5dBfZCd1ip48+8riWN1mK4+npDhljwElugmqvvVdkEY0W2Owc+4VvnQ3E5Q
         Ont3uusfYyZGgggBncluGO+FjIKO5ZnjuOfCnH18fUMl53ssLWW31e+LhXWp8I+9ecRA
         iR62RIptjws091iDbRyKXBMTl+PD9dA6LhJf9g5MaeyhoDh9NQK7xxfQ9IHfDOJWBQ0G
         sg/Q==
X-Gm-Message-State: AOAM5324SUJDHF4tykquasyXXAkhfm7cmRO8zKvXb0LnOVTfhvuR3osR
        5Lm8LUw20Mkn9lqa0Yocga+OkkSOM2U/emAI6ZmJfhEms04P
X-Google-Smtp-Source: ABdhPJyyoBtNWcyZKoBQvMV+DhN/9Y/V39PgXlVbBEI8djWHmarUow57F7HvciEhBxC2QQvxPo7FoWBG5hGAOU5rk0V+sYpYDwPh
MIME-Version: 1.0
X-Received: by 2002:a05:6e02:c:: with SMTP id h12mr14766210ilr.125.1591488195121;
 Sat, 06 Jun 2020 17:03:15 -0700 (PDT)
Date:   Sat, 06 Jun 2020 17:03:15 -0700
X-Google-Appengine-App-Id: s~syzkaller
X-Google-Appengine-App-Id-Alias: syzkaller
Message-ID: <00000000000088d87205a7733830@google.com>
Subject: linux-next test error: BUG: using smp_processor_id() in preemptible
 [ADDR] code: systemd-rfkill/6910
From:   syzbot <syzbot+c2a0ce95f0c47bcd4b37@syzkaller.appspotmail.com>
To:     adilger.kernel@dilger.ca, linux-ext4@vger.kernel.org,
        linux-kernel@vger.kernel.org, linux-next@vger.kernel.org,
        sfr@canb.auug.org.au, syzkaller-bugs@googlegroups.com,
        tytso@mit.edu
Content-Type: text/plain; charset="UTF-8"
Sender: linux-next-owner@vger.kernel.org
Precedence: bulk
List-ID: <linux-next.vger.kernel.org>
X-Mailing-List: linux-next@vger.kernel.org

Hello,

syzbot found the following crash on:

HEAD commit:    0e21d462 Add linux-next specific files for 20200602
git tree:       linux-next
console output: https://syzkaller.appspot.com/x/log.txt?x=1461fcf2100000
kernel config:  https://syzkaller.appspot.com/x/.config?x=ecc1aef35f550ee3
dashboard link: https://syzkaller.appspot.com/bug?extid=c2a0ce95f0c47bcd4b37
compiler:       gcc (GCC) 9.0.0 20181231 (experimental)

IMPORTANT: if you fix the bug, please add the following tag to the commit:
Reported-by: syzbot+c2a0ce95f0c47bcd4b37@syzkaller.appspotmail.com

BUG: using smp_processor_id() in preemptible [00000000] code: systemd-rfkill/6910
caller is ext4_mb_new_blocks+0xa4d/0x3b70 fs/ext4/mballoc.c:4711
CPU: 0 PID: 6910 Comm: systemd-rfkill Not tainted 5.7.0-next-20200602-syzkaller #0
Hardware name: Google Google Compute Engine/Google Compute Engine, BIOS Google 01/01/2011
Call Trace:
 __dump_stack lib/dump_stack.c:77 [inline]
 dump_stack+0x18f/0x20d lib/dump_stack.c:118
 check_preemption_disabled+0x20d/0x220 lib/smp_processor_id.c:48
 ext4_mb_new_blocks+0xa4d/0x3b70 fs/ext4/mballoc.c:4711
 ext4_ext_map_blocks+0x201b/0x33e0 fs/ext4/extents.c:4244
 ext4_map_blocks+0x4cb/0x1640 fs/ext4/inode.c:626
 ext4_getblk+0xad/0x520 fs/ext4/inode.c:833
 ext4_bread+0x7c/0x380 fs/ext4/inode.c:883
 ext4_append+0x153/0x360 fs/ext4/namei.c:67
 ext4_init_new_dir fs/ext4/namei.c:2757 [inline]
 ext4_mkdir+0x5e0/0xdf0 fs/ext4/namei.c:2802
 vfs_mkdir+0x419/0x690 fs/namei.c:3632
 do_mkdirat+0x21e/0x280 fs/namei.c:3655
 do_syscall_64+0x60/0xe0 arch/x86/entry/common.c:359
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7ff18513b687
Code: Bad RIP value.
RSP: 002b:00007ffcc5bd1218 EFLAGS: 00000246 ORIG_RAX: 0000000000000053
RAX: ffffffffffffffda RBX: 0000560bebc67985 RCX: 00007ff18513b687
RDX: 00007ffcc5bd10e0 RSI: 00000000000001ed RDI: 0000560bebc67985
RBP: 00007ff18513b680 R08: 0000000000000100 R09: 0000000000000000
R10: 0000560bebc67980 R11: 0000000000000246 R12: 00000000000001ed
R13: 00007ffcc5bd13a0 R14: 0000000000000000 R15: 0000000000000000


---
This bug is generated by a bot. It may contain errors.
See https://goo.gl/tpsmEJ for more information about syzbot.
syzbot engineers can be reached at syzkaller@googlegroups.com.

syzbot will keep track of this bug report. See:
https://goo.gl/tpsmEJ#status for how to communicate with syzbot.
