Return-Path: <linux-next-owner@vger.kernel.org>
X-Original-To: lists+linux-next@lfdr.de
Delivered-To: lists+linux-next@lfdr.de
Received: from vger.kernel.org (vger.kernel.org [23.128.96.18])
	by mail.lfdr.de (Postfix) with ESMTP id 387783F4C54
	for <lists+linux-next@lfdr.de>; Mon, 23 Aug 2021 16:28:17 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S229743AbhHWO2E (ORCPT <rfc822;lists+linux-next@lfdr.de>);
        Mon, 23 Aug 2021 10:28:04 -0400
Received: from smtp-out2.suse.de ([195.135.220.29]:52664 "EHLO
        smtp-out2.suse.de" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229518AbhHWO2E (ORCPT
        <rfc822;linux-next@vger.kernel.org>); Mon, 23 Aug 2021 10:28:04 -0400
Received: from relay2.suse.de (relay2.suse.de [149.44.160.134])
        by smtp-out2.suse.de (Postfix) with ESMTP id 80FD31FFFE;
        Mon, 23 Aug 2021 14:27:20 +0000 (UTC)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=suse.de; s=susede2_rsa;
        t=1629728840; h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=EZ85niMAovewL2xICo9PxkuxXtrm6xOQQrve0tLgZR4=;
        b=wrP6V/C1KqdNjRhu2a/AgZEwFoiZz5HCFW5I4GqaVeCCwfX0DJpCKKcn2lxEeWgO5EZnVa
        dxdwiRz/5UJTroz9pej1YXp7FvEWXnP6e3LVRqS98vwk1/mOXrxteDG1D9evT9WH5VTJP7
        TXTcMJVxCKiDNlufCVBSYV4ub8rMBjk=
DKIM-Signature: v=1; a=ed25519-sha256; c=relaxed/relaxed; d=suse.de;
        s=susede2_ed25519; t=1629728840;
        h=from:from:reply-to:date:date:message-id:message-id:to:to:cc:cc:
         mime-version:mime-version:content-type:content-type:
         in-reply-to:in-reply-to:references:references;
        bh=EZ85niMAovewL2xICo9PxkuxXtrm6xOQQrve0tLgZR4=;
        b=cwsO99hGvGvx/pte/yoNoRMVkWat3aqD9qvt4T8wZpYXK+zdh3DowlKQ8/XKdJuiIc4JWs
        FnYOa/jrjp9NsoAw==
Received: from alsa1.suse.de (alsa1.suse.de [10.160.4.42])
        by relay2.suse.de (Postfix) with ESMTP id 6F6EFA3BB2;
        Mon, 23 Aug 2021 14:27:20 +0000 (UTC)
Date:   Mon, 23 Aug 2021 16:27:20 +0200
Message-ID: <s5h4kbg44on.wl-tiwai@suse.de>
From:   Takashi Iwai <tiwai@suse.de>
To:     Stephen Rothwell <sfr@canb.auug.org.au>
Cc:     Linux Kernel Mailing List <linux-kernel@vger.kernel.org>,
        Linux Next Mailing List <linux-next@vger.kernel.org>
Subject: Re: linux-next: build warning after merge of the sound tree
In-Reply-To: <20210823200002.45fbc553@canb.auug.org.au>
References: <20210823200002.45fbc553@canb.auug.org.au>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
Content-Type: text/plain; charset=US-ASCII
Precedence: bulk
List-ID: <linux-next.vger.kernel.org>
X-Mailing-List: linux-next@vger.kernel.org

On Mon, 23 Aug 2021 12:00:02 +0200,
Stephen Rothwell wrote:
> 
> Hi all,
> 
> After merging the sound tree, today's linux-next build (htmldocs)
> produced this warning:
> 
> Documentation/sound/alsa-configuration.rst:2258: WARNING: Unexpected indentation.
> 
> Introduced by commit
> 
>   a39978ed6df1 ("ALSA: doc: Add the description of quirk_flags option for snd-usb-audio")

Thanks for the report, now the fix was queued:
  https://lore.kernel.org/r/20210823113518.30134-1-tiwai@suse.de


Takashi
